random_state: 42

data:
  metadata: file:./data/metadata.yml
  inputs:
    - y-Amplitude
    - z-Amplitude
    - Growth-rate
  outputs:
    - Estimated-Failure-Time
  train_test_split: 0.8
  transforms:
    - class_path: agenc.transforms.StandardScaler

learner:
  class_path: agenc.simple_dense.SimpleDense
  init_arguments:
    learning_rate: 1e-2
    batch_size: 64

metrics:
  - class_path: agenc.metrics.RMSE
  - class_path: agenc.metrics.MAE
