seed: 42

data:
  metadata: file:./data/metadata.yaml
  inputs:
    - y-Amplitude
    - z-Amplitude
    - Growth-rate
  outputs:
    - Estimated-Failure-Time
  train_test_split: 0.8
  transforms:
    - class_path: agenc.transforms.Select
      arguments:
        features:
          - y-Amplitude
          - z-Amplitude
          - Growth-rate
          - Estimated-Failure-Time
    - class_path: agenc.transforms.Standardize
      arguments:
        mean:
          y-Amplitude: 0.122053
          z-Amplitude: 0.101741
          Growth-rate: 0.026661
          Estimated-Failure-Time: 2490.564146
        std:
          y-Amplitude: 0.168689
          z-Amplitude: 0.108594
          Growth-rate: 0.016992
          Estimated-Failure-Time: 2477.355746

learner:
  class_path: agenc.learners.simple_dense.SimpleDense
  arguments:
    learning_rate: 1e-2
    batch_size: 64
    max_epochs: 10
    input_size: 3
    output_size: 1

metrics:
  - agenc.metrics.MeanSquaredError
  - agenc.metrics.MeanAbsoluteError
