seed: 42

data:
  metadata: file:./data/metadata.yaml
  inputs:
    - y-Amplitude
    - z-Amplitude
    - Growth-rate
  outputs:
    - Estimated-Failure-Time
  train_test_split: 0.8
  transforms:
    - agenc.transforms.StandardScaler

learner:
  class_path: agenc.simple_dense.SimpleDense
  arguments:
    learning_rate: 1e-2
    batch_size: 64
    max_epochs: 10
    input_size: 3
    output_size: 1

metrics:
  - agenc.metrics.MeanSquaredError
  - agenc.metrics.MeanAbsoluteError
