seed: 42

data:
  loader:
    class_path: agenc.data.UriDataLoader
    arguments:
      uri: file:./data/processed_data.csv
  test_loader:
    class_path: agenc.data.TrainTestSplit
    arguments:
      ratio: 0.8
      shuffle: True
  inputs:
    - y-Amplitude
    - z-Amplitude
    - Growth-rate
  outputs:
    - Estimated-Failure-Time
  transforms:
    - class_path: agenc.transforms.Select
      arguments:
        features:
          - y-Amplitude
          - z-Amplitude
          - Growth-rate
          - Estimated-Failure-Time
    - agenc.transforms.Standardize

learners:
  - name: Simple Dense
    class_path: agenc.learners.simple_dense.SimpleDense
    arguments:
      learning_rate: 1e-2
      batch_size: 64
      max_epochs: 10
      num_workers: 1
      input_size: 3
      output_size: 1

metrics:
  - agenc.metrics.regression.MeanAbsoluteError
