# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coffeeService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coffeeService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63offeeService.proto\x12\x06\x63offee\"z\n\x0b\x43offeeOrder\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12 \n\x04type\x18\x02 \x01(\x0e\x32\x12.coffee.CoffeeType\x12 \n\x04size\x18\x03 \x01(\x0e\x32\x12.coffee.CoffeeSize\x12\x15\n\rcustomer_name\x18\x04 \x01(\t\"n\n\x11MakeCoffeeRequest\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.coffee.CoffeeType\x12 \n\x04size\x18\x02 \x01(\x0e\x32\x12.coffee.CoffeeSize\x12\x15\n\rcustomer_name\x18\x03 \x01(\t\"6\n\x12MakeCoffeeResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\")\n\x15GetOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\":\n\x16GetOrderStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t*X\n\nCoffeeType\x12\x12\n\x0eUNKNOWN_COFFEE\x10\x00\x12\x0c\n\x08\x45SPRESSO\x10\x01\x12\t\n\x05LATTE\x10\x02\x12\x0e\n\nCAPPUCCINO\x10\x03\x12\r\n\tAMERICANO\x10\x04*@\n\nCoffeeSize\x12\x10\n\x0cUNKNOWN_SIZE\x10\x00\x12\t\n\x05SMALL\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\t\n\x05LARGE\x10\x03\x32\xa5\x01\n\rCoffeeService\x12\x43\n\nMakeCoffee\x12\x19.coffee.MakeCoffeeRequest\x1a\x1a.coffee.MakeCoffeeResponse\x12O\n\x0eGetOrderStatus\x12\x1d.coffee.GetOrderStatusRequest\x1a\x1e.coffee.GetOrderStatusResponseB#\n\x12\x63om.example.coffeeB\x0b\x43offeeProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coffeeService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.example.coffeeB\013CoffeeProtoP\001'
  _globals['_COFFEETYPE']._serialized_start=426
  _globals['_COFFEETYPE']._serialized_end=514
  _globals['_COFFEESIZE']._serialized_start=516
  _globals['_COFFEESIZE']._serialized_end=580
  _globals['_COFFEEORDER']._serialized_start=31
  _globals['_COFFEEORDER']._serialized_end=153
  _globals['_MAKECOFFEEREQUEST']._serialized_start=155
  _globals['_MAKECOFFEEREQUEST']._serialized_end=265
  _globals['_MAKECOFFEERESPONSE']._serialized_start=267
  _globals['_MAKECOFFEERESPONSE']._serialized_end=321
  _globals['_GETORDERSTATUSREQUEST']._serialized_start=323
  _globals['_GETORDERSTATUSREQUEST']._serialized_end=364
  _globals['_GETORDERSTATUSRESPONSE']._serialized_start=366
  _globals['_GETORDERSTATUSRESPONSE']._serialized_end=424
  _globals['_COFFEESERVICE']._serialized_start=583
  _globals['_COFFEESERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
