# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import coffeeService_pb2 as coffeeService__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in coffeeService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoffeeServiceStub(object):
    """The coffee service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeCoffee = channel.unary_unary(
                '/coffee.CoffeeService/MakeCoffee',
                request_serializer=coffeeService__pb2.MakeCoffeeRequest.SerializeToString,
                response_deserializer=coffeeService__pb2.MakeCoffeeResponse.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/coffee.CoffeeService/GetOrderStatus',
                request_serializer=coffeeService__pb2.GetOrderStatusRequest.SerializeToString,
                response_deserializer=coffeeService__pb2.GetOrderStatusResponse.FromString,
                _registered_method=True)


class CoffeeServiceServicer(object):
    """The coffee service definition
    """

    def MakeCoffee(self, request, context):
        """Places a coffee order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Gets the status of an existing order
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoffeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeCoffee': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeCoffee,
                    request_deserializer=coffeeService__pb2.MakeCoffeeRequest.FromString,
                    response_serializer=coffeeService__pb2.MakeCoffeeResponse.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=coffeeService__pb2.GetOrderStatusRequest.FromString,
                    response_serializer=coffeeService__pb2.GetOrderStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coffee.CoffeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coffee.CoffeeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoffeeService(object):
    """The coffee service definition
    """

    @staticmethod
    def MakeCoffee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coffee.CoffeeService/MakeCoffee',
            coffeeService__pb2.MakeCoffeeRequest.SerializeToString,
            coffeeService__pb2.MakeCoffeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coffee.CoffeeService/GetOrderStatus',
            coffeeService__pb2.GetOrderStatusRequest.SerializeToString,
            coffeeService__pb2.GetOrderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
