variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: collaborating.tuhh.de:5005/w-6/forschung/agenc/agenc/ci
  tags:
    - tuhh-registry

black:
  script:
    - nox --verbose --session black

ruff:
  script:
    - nox --verbose --session ruff

mypy:
  cache:
    - key: mypy-$CI_COMMIT_REF_SLUG
      paths:
        - .mypy_cache/
  script:
    - nox --verbose --session mypy

test:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11"]
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  script:
    - nox --verbose --session test --python $PYTHON_VERSION

pages:
  script:
    - nox --verbose --session docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
