variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: collaborating.tuhh.de:5005/w-6/forschung/agenc/agenc/ci
  tags:
    - tuhh-registry

black:
  script:
    - nox --verbose --session black

ruff:
  script:
    - nox --verbose --session ruff

mypy:
  cache:
    - key: mypy-$CI_COMMIT_REF_SLUG
      paths:
        - .mypy_cache/
  script:
    - nox --verbose --session mypy

test:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11"]
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  script:
    - nox --verbose --session test --python $PYTHON_VERSION

pages:
  script:
    - nox --verbose --session docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public

deploy:
  before_script:
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
   - eval $(ssh-agent -s)
   - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  script:
   - scp -rP 40043 ./public/* rhlkekke@prod-docker-goldmoon.rz.tuhh.de:/home/rhlkekke/html
  needs: ["pages"]
  rules:
   - if: $CI_COMMIT_REF_NAME == "main"