variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: "collaborating.tuhh.de:5005/w-6/forschung/agenc/agenc/ci"

black:
  script:
    - nox --verbose --session black

ruff:
  script:
    - nox --verbose --session ruff

mypy:
  cache:
    - key: mypy-$CI_COMMIT_REF_SLUG
      paths:
        - .mypy_cache/
  script:
    - nox --verbose --session mypy

test:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11"]
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  script:
    - nox --verbose --session test --python $PYTHON_VERSION
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

examples:
  parallel:
    matrix:
      - EXAMPLE: ["boiler", "failure_time_prediction"]
  retry: 1
  before_script:
    - dvc remote modify --local tuhh-cloud password "${TUHH_CLOUD_SECRET}"
    - dvc pull --recursive examples/$EXAMPLE
  script:
    - nox --verbose --session $EXAMPLE

pages:
  tags:
    - tuhh-registry
  script:
    - nox --verbose --session docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public

deploy-pages:
  tags:
    - tuhh-registry
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - scp -rP 40043 ./public/* rhlkekke@prod-docker-goldmoon.rz.tuhh.de:/home/rhlkekke/html
  needs: ["pages"]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

build-and-deploy-java:
  image: quay.io/buildah/stable:latest
  variables:
    STORAGE_DRIVER: vfs
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE/java-automata-learner"
  before_script:
    - buildah info
    - buildah login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = $tag"
      else
        tag="$CI_COMMIT_SHORT_SHA"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - buildah build --pull --tag "${FQ_IMAGE_NAME}:${tag}" --file java/AutomataLearner/Containerfile java/AutomataLearner
    - buildah push "${FQ_IMAGE_NAME}:${tag}"
  when: manual

build-ci:
  image: quay.io/buildah/stable:latest
  variables:
    STORAGE_DRIVER: vfs
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE/ci"
  before_script:
    - buildah info
    - buildah login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = $tag"
      else
        tag="$CI_COMMIT_SHORT_SHA"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - buildah build --pull --tag "${FQ_IMAGE_NAME}:${tag}" --file .ci/Containerfile .ci
    - buildah push "${FQ_IMAGE_NAME}:${tag}"
  when: manual
