variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - lint
  - build
  - tests
  - docs

default:
  image: python:3.8-slim
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - source venv/bin/activate
    - pip install -e .[dev]

black:
  stage: lint
  image: pyfound/black:23.3.0
  cache: {}
  before_script: []
  script:
    - black --check src/ tests/ run.py

flake8:
  stage: lint
  cache: {}
  before_script:
    - python -m pip install --quiet --upgrade flake8
  script:
    - python -m flake8 --max-line-length=79 --extend-ignore=E306,E501,E203,F401,FE402 src/ tests/ run.py

agenc-setup:
  stage: build
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .cache/pip
      - venv/
  before_script:
    - echo "Skip before_script in build stage"
  script:
    - apt-get update
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .[dev]

test-3.8:
  stage: tests
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .cache/pip
      - venv/
    policy: pull
  before_script:
    - source venv/bin/activate
  script:
    - coverage run --source=src/agenc -m pytest
    - coverage report

test-3.9:
  stage: tests
  image: python:3.9-slim
  before_script:
    - python3 --version
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .[dev]
  script:
    - coverage run --source=src/agenc -m pytest
    - coverage report

test-3.10:
  stage: tests
  image: python:3.10-slim
  before_script:
    - python3 --version
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .[dev]
  script:
    - coverage run --source=src/agenc -m pytest
    - coverage report

test-3.11:
  stage: tests
  image: python:3.11-slim
  before_script:
    - python3 --version
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .[dev]
  script:
    - coverage run --source=src/agenc -m pytest
    - coverage report

pages:
  stage: docs
  image: sphinxdoc/sphinx
  cache: {}
  before_script: []
  script:
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
