variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - lint
  - build
  - tests
  - docs

.python-setup:
  cache:
    paths:
      - .cache/pip
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - python --version; pip --version
    - pip install -e .[test]

black:
  stage: lint
  image: pyfound/black
  script:
    - black --check src/ tests/

flake8:
  stage: lint
  image:
    name: alpine/flake8
    entrypoint: [""]
  script:
    - flake8 --extend-ignore=E501,E203 src/ tests/

agenc-setup:
  extends: .python-setup
  stage: build
  image: python:3.8-slim
  script:
    - python -c "import agenc"

test-3.9:
  extends: .python-setup
  stage: tests
  image: python:3.9-slim
  script:
    - pip install coverage
    - coverage run --source=src/agenc -m pytest
    - coverage report

test-3.10:
  extends: .python-setup
  stage: tests
  image: python:3.10-slim
  script:
    - pip install coverage
    - coverage run --source=src/agenc -m pytest
    - coverage report

test-3.11:
  extends: .python-setup
  stage: tests
  image: python:3.11-slim
  script:
    - pip install coverage
    - coverage run --source=src/agenc -m pytest
    - coverage report

pages:
  stage: docs
  image: sphinxdoc/sphinx
  script:
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
