variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  JOB_SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}

default:
  image: collaborating.tuhh.de:5005/w-6/forschung/agenc/agenc/ci
  tags:
    - tuhh-registry

black:
  script:
    - nox --verbose --session black

ruff:
  script:
    - nox --verbose --session ruff

mypy:
  cache:
    - key: mypy-$CI_COMMIT_REF_SLUG
      paths:
        - .mypy_cache/
  script:
    - nox --verbose --session mypy

test:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11"]
  coverage: "/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/"
  script:
    - nox --verbose --session test --python $PYTHON_VERSION

pages:
  script:
    - nox --verbose --session docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public

.before_upload_script: &before_upload_script
  - apt update; apt install -y openssh-client -y
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null

.upload_docu_script: &upload_docu_script
  - scp -rP "${SSH_PORT}" ./public/* "${SSH_USER}"@"${HOST_NAME}":"${WEBSERVER_ROOT}/"

upload:docu:
  image: ubuntu
  stage: upload
  before_script:
   - *before_upload_script
  script:
   - *upload_docu_script
  rules:
   - if: $CI_COMMIT_REF_NAME == "main"