site_name: Flowcean
theme:
  name: "material"
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle: 
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle: 
        icon: material/weather-night
        name: Switch to light mode
      primary: custom

plugins:
  - mkdocstrings
  - search
  - literate-nav:
      implicit_index: true

markdown_extensions:
  - footnotes
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

watch:
  - src