[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agenc"
version = "0.0.1"
authors = [
    { name="Stephan Balduin", email="stephan.balduin@offis.de" },
    { name="Your Name here", email="your.email@here.de" }
]
description = " "
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "scikit-learn",
    "lightning",
    "tensorboard",
    "polars",
    "ruamel.yaml",
    "pandas",
]

[project.urls]
"Homepage" = "https://collaborating.tuhh.de"
"Bug Tracker" = "https://collaborating.tuhh.de"