[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agenc"
version = "0.1.0"
authors = [
  {name = "The AGenC Team", email = "agenc.team@tuhh.de"}
]
description = "AGenC is a framework to train models for cyber-physical systems."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "numpy",
  "polars",
  "ruamel.yaml",
  "typing-extensions",
]

[project.optional-dependencies]
sklearn = [
  "scikit-learn",
]
lightning = [
  "lightning",
  "tensorboard",
]
grpc = [
  "grpcio",
  "docker",
]
test = [
  "pytest",
  "coverage",
  "scikit-learn",
]
typecheck = [
  "lightning",
  "pytest",
  "argcomplete",
  "protobuf",
  "types-protobuf",
  "grpc-stubs",
]
docs = [
  "mkdocs",
  "mkdocstrings[python]",
  "mkdocs-material",
  "mkdocs-literate-nav",
  "pymdown-extensions",
  "scikit-learn",
  "lightning",
  "docker",
  "grpcio",
  "grpcio-tools",
]
grpc-dev = [
  "grpcio-tools",
  "mypy-protobuf",
]

[tool.black]
line-length = 79
preview = true

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
  "sklearn.*",
  "joblib.*",
  "matplotlib.*",
  "docker.*",
]
ignore_missing_imports = true

[tool.pyright]
ignore = [
  "src/agenc/learners/grpc/_generated/*",
]
pythonVersion = "3.12"

[tool.ruff]
exclude = ["docs", "*_pb2*"]
line-length = 79
target-version = "py310"

[tool.ruff.format]
docstring-code-format=true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN101", # deprecated
  "ANN102", # deprecated
  "ANN401", # dynamically typed expressions (typing.Any) are disallowed
  "D10", # missing docstrings
  "INP001", # implicit namespace packages
  "PD", # pandas
  "PLR0913", # too many arguments
  "T", # print
  "TD002", # missing author in TODO
  "TD003", # missing issue link in TODO
  "S311", # pseudo-random number generation
  "N818", # Error suffix on exceptions
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101", # asserts
  "PLR2004", # Magic value used in comparison
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.coverage.run]
omit = [
  "src/agenc/learners/grpc/_generated/*",
]

[tool.coverage.report]
exclude_also = [
  "pass",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
