[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "agenc"
version = "0.1.0"
authors = [
  {name = "The AGenC Team", email = "agenc.team@tuhh.de"}
]
description = "AGenC is a framework to train models for cyber-physical systems."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "numpy",
  "polars",
  "ruamel.yaml",
  "typing-extensions",
]

[project.optional-dependencies]
sklearn = [
  "scikit-learn",
]
lightning = [
  "lightning",
  "tensorboard",
]
grpc = [
  "grpcio",
]
test = [
  "pytest",
  "coverage",
  "scikit-learn",
]
typecheck = [
  "lightning",
  "pytest",
  "argcomplete",
  "protobuf",
  "types-protobuf",
  "grpc-stubs",
  "mypy",
]
docs = [
  "sphinx",
  "furo",
  "myst-parser",
  "pyenchant",
  "sphinxcontrib-spelling",
  "scikit-learn",
  "lightning",
]
grpc-dev = [
  "grpcio-tools",
  "mypy-protobuf",
]

[project.scripts]
agenc = "agenc.cli:main"

[tool.black]
line-length = 79
preview = true

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
  "sklearn.*",
  "joblib.*",
]
ignore_missing_imports = true

[tool.ruff]
exclude = ["docs", "*pb2*"]
line-length = 79
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "D", "I", "N", "W", "UP", "RUF", "COM", "A", "B", "PT", "Q", "RET", "ARG", "NPY", "PERF"]
ignore = ["D10", "COM812"]

[tool.ruff.lint.pydocstyle]
convention = "google"
