[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agenc"
version = "0.0.2"
authors = [
    { name="Stephan Balduin", email="stephan.balduin@offis.de" },
    { name="Maximilian Schmidt", email="maximilian.schmidt@tuhh.de" },
    { name="Your Name here", email="your.email@here.de" }
]
description = "AGenC Framework"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules", 
]
dependencies = [
    "scikit-learn",
    "polars",
    "ruamel.yaml",
]

[project.optional-dependencies]
test = [
  "pytest",
]
pytorch = [
  "lightning",
  "tensorboard",
]

[project.urls]
"Homepage" = "https://collaborating.tuhh.de"
"Bug Tracker" = "https://collaborating.tuhh.de"

[tool.black]
line-length = 79
preview = true
